const binds = {
  /* movement */
  accel:               "KeyW",
  decel:               "KeyS",
  rotateCW:            "KeyD",
  rotateCCW:           "KeyA",

  toggleAutobrake:     "KeyB",
  activateShields:     "KeyF",
  activateStealth:     "KeyT",
  dismissHint:         "KeyH",
  dockShip:            "KeyG",
  openStationMenu:     "KeyV",
  openInventory:       "KeyI",
  openWorldMap:        "KeyM",
  openMap:             "KeyN",
  interact:            "KeyE",
  scrapDebris:         "KeyC",
  beginCoating:        "KeyQ",
  armWeapons:          "KeyX",
  deathmatchNextArena: "KeyJ",
  boosters:            "Space",
  cancel:              "Escape",
  confirm:             "Enter",
  acceptDialogue:      "KeyZ",
  declineDialogue:     "KeyU",
  openDialogueScreen:  "KeyO",
  pause:               "KeyP",
  skipCutscene:        "Escape",
  replayPage:          "KeyR",
  devIcons:            "Backquote",
  forwardSequence:     "Space",
  showControls:        "F1",

  /* digits */
  selectWeapon0:      "Digit1",
  selectWeapon1:      "Digit2",
  selectWeapon2:      "Digit3",
  selectWeapon3:      "Digit4",
  navMesh:            "Digit5",
  gameStats:          "Digit6",
  hitbox:             "Digit7",
  zoomIn:             "Digit8",
  zoomOut:            "Digit9",
  resetZoom:          "Digit0",
  
  /* modifiers */
  shift:              "ShiftLeft",
  shiftRight:         "ShiftRight",
  ctrl:               "ControlLeft",
  ctrlRight:          "ControlRight",
  alt:                "alt",
}